# Obsidian Ghostty Theme

# Primary colors
background = #080b0e
foreground = #d1d1d1

# Normal colors
palette = 1=#000000
palette = 2=#bd053d
palette = 3=#03BE8C
palette = 4=#fdb602
palette = 5=#8800ff
palette = 6=#b0006c
palette = 7=#02a2ff
palette = 8=#E5E9F0
