# preload = /home/mando/Pictures/wallpaper/M1.png
# wallpaper = , /home/mando/Pictures/wallpaper/M1.png

wallpaper {
    monitor = eDP-2
    path = ~/Pictures/wallpaper/M2.png
    fit_mode = cover
}

splash = false